#!/bin/sh
file=`basename $0`
num=$1
host="host${num}"
target="target${num}:0:0"
timeout_sec=10
count_sec=0

# rescan bus
dev_host="/sys/class/scsi_host/${host}"
if [ -d "$dev_host" ]; then
	echo "- - -" > ${dev_host}/scan
else
	exit 1
fi

# check disk device is existed
dev_target="${dev_host}/device/${target}"
while [ ${count_sec} -lt ${timeout_sec} ]; do
	if [ -d "${dev_target}" ]; then
		echo "mxhtspd: Disk slot $num was detected." | wall -n
		exit 0
	fi
	count_sec=$((count_sec + 1))
	sleep 1
done
